# Generated by Django 2.1.1 on 2018-09-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_auto_20180927_0736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
