# Generated by Django 2.1.1 on 2018-09-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0004_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
